// Puzzle description: https://adventofcode.com/2024/day/17

#[derive(Debug, Clone)]
struct Computer {
    a: u64,
    b: u64,
    c: u64,
    ptr: usize,
    stack: Vec<u64>,
    output: Vec<u64>,
}

impl Computer {
    fn parse(input: &str) -> Computer {
        fn read_end_nb(line: &str) -> u64 {
            line.rsplit_once(' ').unwrap().1.parse().unwrap()
        }
        fn read_end_nbs(line: &str) -> Vec<u64> {
            let csvs = line.rsplit_once(' ').unwrap().1;
            csvs.split(',').map(|s| s.parse().unwrap()).collect()
        }
        let mut lines = input.lines();
        let a = read_end_nb(lines.next().unwrap());
        let b = read_end_nb(lines.next().unwrap());
        let c = read_end_nb(lines.next().unwrap());
        lines.next(); // Skip empty line
        let stack = read_end_nbs(lines.next().unwrap());
        Computer {
            a,
            b,
            c,
            ptr: 0,
            stack,
            output: Vec::new(),
        }
    }
    fn combo(&self) -> u64 {
        let op = self.stack[self.ptr + 1];
        match op {
            x if (0..=3).contains(&x) => x,
            4 => self.a,
            5 => self.b,
            6 => self.c,
            _ => panic!("tried to eval invalid combo opcode"),
        }
    }
    fn literal(&self) -> u64 {
        self.stack[self.ptr + 1]
    }
    fn tick(&mut self) -> bool {
        if let Some(opcode) = self.stack.get(self.ptr) {
            match opcode {
                // adv
                0 => {
                    self.a >>= self.combo();
                    self.ptr += 2;
                }
                // bxl
                1 => {
                    self.b ^= self.literal();
                    self.ptr += 2;
                }
                // bst
                2 => {
                    self.b = self.combo() % 8;
                    self.ptr += 2;
                }
                // jnz
                3 => {
                    if self.a == 0 {
                        self.ptr += 2;
                    } else {
                        self.ptr = self.literal().try_into().unwrap();
                    }
                }
                // bxc
                4 => {
                    self.b ^= self.c;
                    self.ptr += 2;
                }
                // out
                5 => {
                    self.output.push(self.combo() % 8);
                    self.ptr += 2;
                }
                // bdv
                6 => {
                    self.b = self.a >> self.combo();
                    self.ptr += 2;
                }
                // cdv
                7 => {
                    self.c = self.a >> self.combo();
                    self.ptr += 2;
                }
                _ => {
                    panic!("invalid opcode encountered");
                }
            };
            true
        } else {
            false
        }
    }
}

/* Decompiling the input program:
Program: 2,4,1,5,7,5,4,5,0,3,1,6,5,5,3,0
Translated:
    2: b = a % 8
    4:
    1: b = b ^ 5
    5:
    7: c = a >> b
    5:
    4: b = b ^ c
    5:
    0: a = a >> 3
    3:
    1: b = b ^ 6
    6:
    5: output b % 8
    5:
    3: if a != 0 loop
    0
Simplify code:
    b = a % 8
    b = b ^ 5
      = (a % 8) ^ 5
    c = a >> b
      = a >> ((a % 8) ^ 5)
    b = b ^ c
      = ((a % 8) ^ 5) ^ (a >> ((a % 8) ^ 5))
    a2= a >> 3
    b = b ^ 6
      = (((a % 8) ^ 5) ^ (a >> ((a % 8) ^ 5))) ^ 6
    output b % 8
      = ((((a % 8) ^ 5) ^ (a >> ((a % 8) ^ 5))) ^ 6) % 8
    if a2 != 0
        a = a2
        loop
I.e.
    loop {
        ouput ((((a % 8) ^ 5) ^ (a >> ((a % 8) ^ 5))) ^ 6) % 8
        a = a >> 3
        if a == 0 break
    }
Simplify output expression:
    ((((a % 8) ^ 5) ^ (a >> ((a % 8) ^ 5))) ^ 6) % 8
    let x = a % 8 = a & 7
        = (((x ^ 5) ^ (a >> (x ^ 5))) ^ 6) % 8
    x elem [0,7]
    a & 7 uses bits [0,2]
    (a >> x) & 7 uses bits [_, 2+7 = 9]
    so output depends only on a bits [0,9]
    so output i depends only on a bits [3i, 3i+9]
*/

// Output i generated by the given initial a register.
fn get_output(a: u64, i: usize) -> u64 {
    let a = a >> (3 * i);
    let b = a % 8;
    let b = b ^ 5;
    let c = a >> b;
    let b = b ^ c;
    let b = b ^ 6;
    b % 8
}

// Smallest register a value, that differs from the given suffix only in bits [3i, 3i+2],
// that yields the given i-th output value.
// The bit limitation is so that it does not alter output i+1.
fn find_next_a(suffix: u64, i: usize, output: u64) -> impl Iterator<Item = u64> {
    // Output i depends on bits [3i, 3i+9]
    // Output i+1 depends on [3i+3, 3i+12]
    // To not alter output i+1, we only modify bits [3i, 3i+2]
    let max_prefix = 1 << (3 * i + 3);
    let step = 1 << (3 * i);
    (0..max_prefix)
        .step_by(step)
        .map(move |prefix| suffix + prefix)
        .filter(move |&a| get_output(a, i) == output)
}

// The lowest initial register a value that yields the given output.
fn find_a(suffix: u64, output: &[u64]) -> Option<u64> {
    let n = output.len();
    if n == 0 {
        Some(suffix)
    } else {
        // Search from the end, because that corresponds to the
        // most significant bits of a, which we want to be lowest,
        // and not have to pick higher bits because a preceding
        // solution excluded the lower ones.
        let i = n - 1;
        let x = output[i];
        find_next_a(suffix, i, x)
            .filter_map(|suffix| find_a(suffix, &output[..i]))
            .next()
    }
}

const INPUT: &str = "data/y2024/d17/input";

pub fn part1() -> String {
    let input = std::fs::read_to_string(INPUT).unwrap();
    let mut c = Computer::parse(&input);
    while c.tick() {}
    let s: Vec<String> = c.output.iter().map(|x| x.to_string()).collect();
    s.join(",")
}

pub fn part2() -> u64 {
    let input = std::fs::read_to_string(INPUT).unwrap();
    let c = Computer::parse(&input);
    find_a(0, &c.stack).unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_part1() {
        assert_eq!(part1(), "3,4,3,1,7,6,5,6,0");
    }
    #[test]
    fn test_part2() {
        assert_eq!(part2(), 109019930331546);
    }
}
